// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: dataguard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DataGuard_Analyze_FullMethodName = "/dataguard.DataGuard/Analyze"
	DataGuard_Check_FullMethodName   = "/dataguard.DataGuard/Check"
)

// DataGuardClient is the client API for DataGuard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGuardClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type dataGuardClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGuardClient(cc grpc.ClientConnInterface) DataGuardClient {
	return &dataGuardClient{cc}
}

func (c *dataGuardClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, DataGuard_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataGuardClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, DataGuard_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGuardServer is the server API for DataGuard service.
// All implementations must embed UnimplementedDataGuardServer
// for forward compatibility
type DataGuardServer interface {
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedDataGuardServer()
}

// UnimplementedDataGuardServer must be embedded to have forward compatible implementations.
type UnimplementedDataGuardServer struct {
}

func (UnimplementedDataGuardServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedDataGuardServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedDataGuardServer) mustEmbedUnimplementedDataGuardServer() {}

// UnsafeDataGuardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGuardServer will
// result in compilation errors.
type UnsafeDataGuardServer interface {
	mustEmbedUnimplementedDataGuardServer()
}

func RegisterDataGuardServer(s grpc.ServiceRegistrar, srv DataGuardServer) {
	s.RegisterService(&DataGuard_ServiceDesc, srv)
}

func _DataGuard_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuardServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGuard_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuardServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataGuard_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGuardServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataGuard_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGuardServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGuard_ServiceDesc is the grpc.ServiceDesc for DataGuard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGuard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataguard.DataGuard",
	HandlerType: (*DataGuardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _DataGuard_Analyze_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _DataGuard_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataguard.proto",
}
