name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  triage:
    if: github.actor == 'dependabot[bot]'
    uses: flipslidersand-labs/qa-workflows/.github/workflows/dependabot-auto-merge.yml@d114211a23c11813b0dcc886c0aa5e9c10f6585d
